name: perfect_wedding_planner
description: A comprehensive wedding planning application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  retrofit: ^4.1.0
  connectivity_plus: ^5.0.2
  go_router: ^13.2.0
  go_router_builder: ^2.4.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  table_calendar: ^3.0.9
  shimmer: ^3.0.0
  url_launcher: ^6.2.4
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
#  fonts:
#    - family: Montserrat
#      fonts:
#        - asset: assets/fonts/Montserrat-Regular.ttf
#        - asset: assets/fonts/Montserrat-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Montserrat-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/Montserrat-Bold.ttf
#          weight: 700
#    - family: Playfair
#      fonts:
#        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
#        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
#          weight: 700